workflows:
  ios-build:
    name: Build iOS WebView App
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - atharjaveria7@gmail.com
